### ISSUE TITLE
Skeletons listing isn't working

### ISSUE THREAD

**Issue by balupton** [docpad/website#70]
![screenshot 2015-08-19 18 16 26](https://cloud.githubusercontent.com/assets/61148/9353884/6fc1df8c-469e-11e5-9048-df05c6de1cdf.png)

**Comment by balupton** [comment]
Looking at logs, it provides:

```
    → [2015-08-19 10:32:48.701] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:337] [readFile]
debug: Feedr is parsing [http://helper.docpad.org/exchange.cson?version=6.78.1] on [/home/ubuntu/tmp/1be7798e424a411ad1424312bb1ef1f2.cson-meta.json]
    → [2015-08-19 10:32:48.703] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:357] [readMetaFile]
debug: Feedr is reading [http://helper.docpad.org/exchange.cson?version=6.78.1] on [/home/ubuntu/tmp/1be7798e424a411ad1424312bb1ef1f2.cson-meta.json], checking exists
    → [2015-08-19 10:32:48.704] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:337] [readFile]
debug: Feedr is reading [http://helper.docpad.org/latest.json] on [/home/ubuntu/tmp/af1eae4f82f9692179dc4e0720e68bb2.json-meta.json], it doesn't exist
    → [2015-08-19 10:32:48.706] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:340] [unknown]
debug: Feedr is parsing [http://helper.docpad.org/latest.json] on [/home/ubuntu/tmp/af1eae4f82f9692179dc4e0720e68bb2.json-meta.json], read failed null
    → [2015-08-19 10:32:48.707] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:361] [unknown]
debug: Feedr is fetching [http://helper.docpad.org/latest.json] to [/home/ubuntu/tmp/af1eae4f82f9692179dc4e0720e68bb2.json], requesting
    → [2015-08-19 10:32:48.708] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:446] [viaRequest]
debug: Feedr is reading [http://helper.docpad.org/exchange.cson?version=6.78.1] on [/home/ubuntu/tmp/1be7798e424a411ad1424312bb1ef1f2.cson-meta.json], it doesn't exist
    → [2015-08-19 10:32:48.713] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:340] [unknown]
debug: Feedr is parsing [http://helper.docpad.org/exchange.cson?version=6.78.1] on [/home/ubuntu/tmp/1be7798e424a411ad1424312bb1ef1f2.cson-meta.json], read failed null
    → [2015-08-19 10:32:48.714] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:361] [unknown]
debug: Feedr is fetching [http://helper.docpad.org/exchange.cson?version=6.78.1] to [/home/ubuntu/tmp/1be7798e424a411ad1424312bb1ef1f2.cson], requesting
    → [2015-08-19 10:32:48.715] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:446] [viaRequest]
debug: Feedr is fetching [http://helper.docpad.org/exchange.cson?version=6.78.1] to [/home/ubuntu/tmp/1be7798e424a411ad1424312bb1ef1f2.cson], requested
    → [2015-08-19 10:32:48.895] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:460] [Request._callback]
debug: Feedr parse [http://helper.docpad.org/exchange.cson?version=6.78.1] with cson attempt
    → [2015-08-19 10:32:48.896] [/home/ubuntu/website/node_modules/docpad-plugin-feedr/node_modules/feedr/out/lib/feedr.js:245] [generateParser]
```

Which isnt; that useful.

**Comment by nelsonam** [comment]
I'm seeing this: 
<img width="1715" alt="screen shot 2015-08-22 at 10 15 45 am" src="https://cloud.githubusercontent.com/assets/557945/9425032/c9fea9a2-48b6-11e5-9dc0-30a788a68c7a.png">

**Comment by balupton** [comment]
@nelsonam thanks, that's what I'm seeing too

I've been looking at this all week, and can't figure it out at all - locally it works fine, but for some reason remotely it fails - I have a few suspicions of things that I'll continue to address, which should be resolved within another week - however, if it still fails then, then I'll need to somehow get into the travisci build and find out what's going on

**Comment by Sequoia** [comment]
? is there a fallback listing?

**Comment by handylearn** [comment]
Problem is still there. A project that claims to be able to build satic website should be able to solve this problem. Maybe the community can help here. How is the list supposed to be generated?

**Comment by balupton** [comment]
> Problem is still there. 

Yes, which is why this issue is not closed.

> A project that claims to be able to build static websites should be able to solve this problem. 

That's a bit douchey.

> Maybe the community can help here. How is the list supposed to be generated?

Kind of the point of my earlier comment. I can't figure it out.

How it works is as follows:

1. Website pulls in the skeleton list via this feedr plugin configuration: https://github.com/docpad/website/blob/67877cd2fdc6d39fff5456170f116cf571c8f5e8/docpad.coffee#L353-L355 / https://github.com/docpad/website/blob/67877cd2fdc6d39fff5456170f116cf571c8f5e8/docpad.coffee#L47
2. Feedr plugin uses bevry/feedr
3. The data should be injected into `this.feedr.feeds.exchange`
4. It should be rendered by https://github.com/docpad/documentation/blob/13581abed26331f8c16b79468f42d076a43c0090/community/skeletons.html.md.eco#L7-L24 which is pulled in by the repocloner plugin

The helper is currently down as reported by https://github.com/docpad/docpad/issues/1027

**Comment by dunphyben** [comment]
Newbie to docpad here. Found out about it through the Netlify blog.

Not sure if this will help but this is what I'm seeing when I enter $`docpad run`:

![A screenshot of my terminal that shows an error service unavailable when attempting to reach the skeleton list](http://i.imgur.com/JIP0HpD.png)

In the meantime while this issue is being worked on, is there a way to integrate a skeleton either after an empty project has been set up, or to force it to run with a skeleton from command-line setup?

**Comment by balupton** [comment]
@dunphyben 

Thanks.

> In the meantime while this issue is being worked on, is there a way to integrate a skeleton either after an empty project has been set up, or to force it to run with a skeleton from command-line setup?

Sure. Just pick out a skeleton from https://github.com/docpad/extras/blob/docpad-6.x/exchange.cson and clone out the repo url, switch to that branch, and run `npm install` inside it. Skeletons are just git repositories on particular branches.

**Comment by dcsan** [comment]
I had a docpad setup but then removed the submodule, seems to have broken my site. I'm trying to follow the above, its a bit unclear.

where should the skeleton repo be checked out to?
I put it inside the docpad site, but still failing.

```
$ npm run start

> casper-skeleton.docpad@0.1.0 start /root/www/chatrobot/wiki
> docpad-server

module.js:328
    throw err;
    ^

Error: Cannot find module '../out/bin/docpad-server'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/www/chatrobot/wiki/node_modules/.bin/docpad-server:3:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

```

I cloned `docpad-skeleton-casper` inside the node_modules folder of the deploy ready install
FWIW the site runs on my local machine, so there are obviously some dependencies that are global somewhere with the docpad install.

```
├── docpad.coffee
├── LICENSE
├── node_modules
│   ├── docpad-plugin-rss
│   ├── docpad-plugin-tags
│   ├── docpad-skeleton-casper
│   ├── .... etc

├── npm-debug.log
├── out
├── package.json
├── README.md
└── src
```

**Comment by dcsan** [comment]
```
root@dev1:~/www/chatrobot/wiki# cat package.json 
{
  "name": "casper-skeleton.docpad",
  "version": "0.1.0",
  "description": "The Casper theme for Docpad",
  "dependencies": {
    "docpad": "~6.78.1",
    "docpad-plugin-eco": "~2.1.0",
    "docpad-plugin-livereload": "~2.7.1",
    "docpad-plugin-marked": "~2.3.0",
    "docpad-plugin-paged": "~2.4.0",
    "docpad-plugin-partials": "~2.9.2",
    "docpad-plugin-rss": "~2.2.0",
    "docpad-plugin-tags": "~2.0.7",
    "moment": "^2.10.3"
  },
  "main": "node_modules/.bin/docpad-server",
  "scripts": {
    "start": "node_modules/.bin/docpad-server"
  }
}
```

**Comment by dcsan** [comment]
hmm, I can run with `docpad run -e production` so maybe the script that's left in the package.json shouldn't be there?

```json
  "scripts": {
    "start": "node_modules/.bin/docpad-server"
  }
```

**Comment by dcsan** [comment]
after installing docpad globally I can run on the server. so I guess its just that the package.json isn't fully self contained, docpad itself also needs to be `npm install -g` to be able to serve in production mode? This isn't related to templates, sorry for hijacking the thread.

**Comment by balupton** [comment]
> I cloned docpad-skeleton-casper inside the node_modules folder of the deploy ready install
FWIW the site runs on my local machine, so there are obviously some dependencies that are global somewhere with the docpad install.

Skeletons are not plugins that go inside `node_modules`. They are git repositories that serve as a starter kit for a new website.

E.g.

```
npm install -g docpad

cd Projects
git clone https://github.com/docpad/docpad-skeleton-h5bp.git my-new-docpad-website
cd my-new-docpad-website
npm install
docpad run
```

**Comment by nevetS** [comment]
This is still broken.

**Comment by balupton** [comment]
I've looked into this several times and no clue. Giving up on my side.

Will revaluate once again after the DocPad to JavaScript conversion has completed: https://github.com/docpad/docpad/issues/1046

**Comment by balupton** [comment]
for now https://github.com/search?q=topic%3Adocpad-project can be used

**Comment by balupton** [comment]
got it working by converting the listing to json and updating the helper to use the json extension and to have the docpad website fetch the extensionless helper URL

it is now over at https://docpad.org/docs/showcase#skeletons

**Comment by balupton** [comment]
Finally fixed this. Swapped out the feedr plugin for the downloader plugin.

So it is definitely something broken about feedr.
